### ISSUE TITLE
using meta programming way to execute methods

### ISSUE THREAD

**Issue by blackestwhite** [gothinkster/vue-realworld-example-app#114]
Hey,
what's the reason that using this way of declaring functions?
`
const mutations = {
  [SET_PROFILE] (state, profile){
    state.profile = profile;
    state.errors = {};
  }
}
`
what is advantages of using meta programming?
I'm not experienced, sorry if my question was ridiculous.

**Comment by igeligel** [comment]
Hi, the question is ridiculous. Thanks for asking :)

```js
const mutations = {
  [SET_PROFILE](state, profile) {
    state.profile = profile;
    state.errors = {};
  }
};
```

By importing `SET_PROFILE` as a variable we make sure that if we rename the actual value of the mutation, it will be changed automatically in other places too. So this is just a nice-to-have feature. A good use-case, for example, is, when you actually want to change the name in the dev tools of this mutation because this can be done easily now by just renaming the value of the variable.

The JavaScript feature we are using here is called 'computed property names'. You can find more information on MDN here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Object_literals
