### ISSUE TITLE
Upgrade to vue-cli 3

### ISSUE THREAD

**Issue by igeligel** [gothinkster/vue-realworld-example-app#23]
When [vue-cli](https://github.com/vuejs/vue-cli) is getting released in version 3 we should upgrade the project structure. I can do this when it will be time. Just creating this issue to keep track of it.

Right now it is in `beta.6`.

**Comment by igeligel** [comment]
Now the new CLI is finally released and we should migrate to this. I will look into this at the weekend if i can find some time.

**Comment by tecfu** [comment]
@igeligel Do you have an active channel of communication with the maintainers outside of Github? This repo seems abandoned. 

It would be great to see you implement vue-cli, however.

**Comment by vilsbole** [comment]
We don’t have any for the moment, but I would be glad to open one.
Any preferences?


On 4 September 2018 at 10:57:39, tecfu (notifications@github.com) wrote:

@igeligel <https://github.com/igeligel> Do you have an active channel of
communication with the maintainers outside of Github? This repo seems
abandoned.

It would be great to see you implement vue-cli, however.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gothinkster/vue-realworld-example-app/issues/23#issuecomment-418292982>,
or mute the thread

**Comment by tecfu** [comment]
@vilsbole I made that comment because I did submit a couple of pull requests (https://github.com/gothinkster/vue-realworld-example-app/pull/49, https://github.com/gothinkster/vue-realworld-example-app/pull/48) previously, and didn't see any activity. 

I'm glad there's finally some action today.

**Comment by igeligel** [comment]
We could open a discord. Official vue chat is also on discord :+1:

**Comment by tecfu** [comment]
I've never used it but I think its better than nothing. I would also mention IRC via freenode as an option.

**Comment by vilsbole** [comment]
Since Vuejs is on discord I created a discord channel for vue-realworld.
The channel link has been added to the readme.
https://discord.gg/NE2jNmg

@tecfu
It also seems possible to configure a relay between discord and irc:
https://www.npmjs.com/package/discord-irc

I look forward to seeing you all on the channel!

On 4 September 2018 at 13:19:41, tecfu (notifications@github.com) wrote:

I've never used it but I think its better than nothing. I would also
mention IRC via freenode as an option.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gothinkster/vue-realworld-example-app/issues/23#issuecomment-418330101>,
or mute the thread

**Comment by tecfu** [comment]
@vilsbole joined. Thanks.

**Comment by igeligel** [comment]
Created a PR #57

**Comment by igeligel** [comment]
Done with eeaeb34fa440d00cd400545301ea203bd2a59284
